"use client";
import { useDeferredValue, useEffect, useMemo, useState, type FormEvent } from "react";
import { DndContext, DragOverlay, KeyboardSensor, PointerSensor, closestCorners, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Activity, ArrowDown, ArrowRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Command, GripVertical, LayoutGrid, ListFilter, MoreHorizontal, Plus, Search, Settings2, Sparkles, Users, X } from "lucide-react";

type Status="Backlog"|"In progress"|"In review"|"Done";
type Task={id:string;title:string;description:string;label:string;status:Status;priority:"High"|"Medium"|"Low";assignee:string;due:string;checklist?:string};
type ActivityItem={id:string;message:string;time:string};
const statuses:Status[]=["Backlog","In progress","In review","Done"];
const members=[{id:"sj",name:"Saurabh Jaju",initials:"SJ",tone:"sage"},{id:"al",name:"Alex Lee",initials:"AL",tone:"blue"},{id:"mk",name:"Mei Kim",initials:"MK",tone:"lilac"},{id:"pn",name:"Priya Nair",initials:"PN",tone:"peach"}];
const seed:Task[]=[
 {id:"CP-42",title:"Map the first-run workspace journey",description:"Review where a new team needs guidance without adding extra setup steps.",label:"Product",status:"Backlog",priority:"Medium",assignee:"mk",due:"Oct 04",checklist:"1/3"},
 {id:"CP-39",title:"Audit empty states across the board",description:"Make the next action clear when there are no projects or tasks yet.",label:"Design",status:"Backlog",priority:"Low",assignee:"pn",due:"Oct 06"},
 {id:"CP-36",title:"Define project activity event model",description:"Agree on the event vocabulary for task changes, comments, and membership.",label:"Platform",status:"Backlog",priority:"High",assignee:"sj",due:"Oct 03"},
 {id:"CP-41",title:"Build keyboard-friendly task movement",description:"Make status changes and ordering work without relying on drag gestures.",label:"Accessibility",status:"In progress",priority:"High",assignee:"al",due:"Oct 02",checklist:"2/4"},
 {id:"CP-38",title:"Create a shared label color system",description:"Define contrast-safe color and text pairs for project labels.",label:"Design",status:"In progress",priority:"Medium",assignee:"mk",due:"Oct 03"},
 {id:"CP-34",title:"Document workspace permission rules",description:"Write down the boundary between owners, members, and read-only guests.",label:"Platform",status:"In progress",priority:"Medium",assignee:"sj",due:"Oct 05"},
 {id:"CP-40",title:"Review task card hierarchy",description:"Check status, owner, due date, and priority at a glance.",label:"Design",status:"In review",priority:"Medium",assignee:"pn",due:"Oct 01",checklist:"3/3"},
 {id:"CP-37",title:"Add accessible board landmarks",description:"Add meaningful headings and labels for assistive technology navigation.",label:"Accessibility",status:"In review",priority:"High",assignee:"al",due:"Oct 01"},
 {id:"CP-33",title:"Set up preview deployment workflow",description:"Create a repeatable path from pull request to reviewable environment.",label:"Platform",status:"Done",priority:"Low",assignee:"sj",due:"Sep 29"},
 {id:"CP-31",title:"Collect team planning feedback",description:"Summarize where handoffs and task ownership currently feel unclear.",label:"Product",status:"Done",priority:"Low",assignee:"mk",due:"Sep 26"},
];
const statusTone=(s:Status)=>s.toLowerCase().replaceAll(" ","-");

export default function Home(){
 const [tasks,setTasks]=useState(seed),[activity,setActivity]=useState<ActivityItem[]>([{id:"a1",message:"Mei Kim moved task CP-40 to In review",time:"12 min ago"},{id:"a2",message:"Alex Lee completed checklist on CP-41",time:"38 min ago"},{id:"a3",message:"Saurabh Jaju added a task to Backlog",time:"1 hour ago"}]),[query,setQuery]=useState(""),[filter,setFilter]=useState("All work"),[modal,setModal]=useState(false),[draft,setDraft]=useState({title:"",description:"",label:"Product",priority:"Medium" as Task["priority"],assignee:"sj",due:""}),[active,setActive]=useState<Task|null>(null),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
 const deferredQuery=useDeferredValue(query),sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 useEffect(()=>{try{const saved=localStorage.getItem("commonplace-board");if(saved){const d=JSON.parse(saved);if(d.tasks)setTasks(d.tasks);if(d.activity)setActivity(d.activity);}}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)localStorage.setItem("commonplace-board",JSON.stringify({tasks,activity}));},[tasks,activity,ready]);
 const matching=useMemo(()=>tasks.filter(t=>(filter!=="My work"||t.assignee==="sj")&&`${t.title} ${t.description} ${t.label} ${t.id}`.toLowerCase().includes(deferredQuery.toLowerCase())),[tasks,filter,deferredQuery]);
 const pushActivity=(msg:string)=>setActivity([{id:crypto.randomUUID(),message:msg,time:"Just now"},...activity].slice(0,10));
 const moveTask=(task:Task,status:Status)=>{if(task.status===status)return;setTasks(tasks.map(t=>t.id===task.id?{...t,status}:t));pushActivity(`You moved ${task.id} to ${status}`);setNotice(`${task.id} moved to ${status}.`);window.setTimeout(()=>setNotice(""),2200);};
 const handleDragStart=(e:{active:{id:string|number}})=>setActive(tasks.find(t=>t.id===e.active.id)??null);
 const handleDragEnd=(e:DragEndEvent)=>{const {active:dragged,over}=e;setActive(null);if(!over)return;const source=tasks.find(t=>t.id===dragged.id);if(!source)return;const targetId=String(over.id);const target=tasks.find(t=>t.id===targetId);const dest=(target?.status??(statuses.includes(targetId.replace("column:","") as Status)?targetId.replace("column:","") as Status:source.status));if(dest!==source.status){moveTask(source,dest);return;}if(target&&target.status===source.status&&target.id!==source.id){const group=tasks.filter(t=>t.status===source.status);const moved=arrayMove(group,group.findIndex(t=>t.id===source.id),group.findIndex(t=>t.id===target.id));const order=new Map(moved.map((t,i)=>[t.id,i]));setTasks([...tasks].sort((a,b)=>a.status===b.status?(order.get(a.id)??0)-(order.get(b.id)??0):statuses.indexOf(a.status)-statuses.indexOf(b.status)));}};
 const addTask=(e:FormEvent)=>{e.preventDefault();if(!draft.title.trim())return;const task:Task={id:`CP-${Math.floor(43+Math.random()*900)}`,title:draft.title.trim(),description:draft.description.trim(),label:draft.label,status:"Backlog",priority:draft.priority,assignee:draft.assignee,due:draft.due||"No due date"};setTasks([task,...tasks]);pushActivity(`You created ${task.id} in Backlog`);setDraft({title:"",description:"",label:"Product",priority:"Medium",assignee:"sj",due:""});setModal(false);setNotice("Task added to Backlog.");window.setTimeout(()=>setNotice(""),2200);};
 const dueSoon=tasks.filter(t=>t.status!=="Done"&&(t.due==="Oct 01"||t.due==="Oct 02")).length;
 return <main className="workspace-shell">
  <aside className="sidebar"><a className="brand" href="#"><span className="brand-mark"><span/></span><span>commonplace</span></a><button className="workspace-picker"><span className="workspace-avatar">S</span><span><b>Studio North</b><small>Team workspace</small></span><ChevronDown size={14}/></button><div className="side-label">WORKSPACE</div><nav><button className="nav-link active"><LayoutGrid size={17}/>Board</button><button className="nav-link"><ListFilter size={17}/>My tasks<span>{tasks.filter(t=>t.assignee==="sj"&&t.status!=="Done").length}</span></button><button className="nav-link"><Activity size={17}/>Activity</button><button className="nav-link"><Users size={17}/>Members<span>4</span></button></nav><div className="side-label project-label">YOUR PROJECTS <button aria-label="Add project"><Plus size={14}/></button></div><button className="project-link selected"><i/>Website refresh<span>●</span></button><button className="project-link"><i/>Customer portal</button><button className="project-link"><i/>Design system</button><button className="project-link muted"><Plus size={14}/>Create a project</button><div className="sidebar-spacer"/><div className="workspace-tip"><div><Sparkles size={14}/><span>TEAM NOTE</span></div><b>Make space for<br/>the work that matters.</b><small>A little clarity can change a week.</small></div><button className="nav-link bottom-link"><CircleHelp size={16}/>Help & feedback</button><button className="nav-link bottom-link"><Settings2 size={16}/>Settings</button><div className="profile"><span className="profile-avatar">SJ</span><span><b>Saurabh Jaju</b><small>Workspace admin</small></span><MoreHorizontal size={16}/></div></aside>
  <section className="main"><header className="topbar"><div className="breadcrumbs">Studio North <span>/</span> Projects <span>/</span> <b>Website refresh</b></div><div className="top-actions"><label className="global-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks"/><kbd><Command size={9}/> K</kbd></label><button className="icon-button" aria-label="Notifications"><Bell size={16}/><i/></button><div className="avatars-stack" aria-label="4 project members">{members.map(m=><span key={m.id} className={`avatar ${m.tone}`} title={m.name}>{m.initials}</span>)}</div></div></header>
   <div className="content"><div className="project-heading"><div><div className="eyebrow"><span/> WEBSITE REFRESH <span className="dot-sep">·</span> OCTOBER 2026</div><h1>Good work, in motion.</h1><p>A shared view of what’s moving and what needs a hand.</p></div><div className="heading-actions"><button className={`filter-chip ${filter==="My work"?"active":""}`} aria-pressed={filter==="My work"} onClick={()=>setFilter(filter==="My work"?"All work":"My work")}><UserRoundIcon/> My work</button><button className="primary-button" onClick={()=>setModal(true)}><Plus size={15}/> Add task</button></div></div>
    <div className="summary"><div className="summary-copy"><div className="eyebrow">PROJECT MOMENTUM</div><b>{tasks.filter(t=>t.status!=="Done").length} open tasks <span>·</span> {dueSoon} due soon</b><div className="progress-track"><i style={{width:`${Math.round(tasks.filter(t=>t.status==="Done").length/Math.max(1,tasks.length)*100)}%`}}/></div><small>{Math.round(tasks.filter(t=>t.status==="Done").length/Math.max(1,tasks.length)*100)}% of this project is complete</small></div><div className="summary-meta"><div><span>LEAD</span><b><span className="avatar sage">SJ</span> Saurabh Jaju</b></div><div><span>UPDATED</span><b>12 minutes ago</b></div><button aria-label="Project options"><MoreHorizontal size={18}/></button></div></div>
    <div className="board-toolbar"><div className="board-tabs"><button className="selected"><LayoutGrid size={14}/> Board</button><button><Activity size={14}/> Timeline <span>SOON</span></button></div><div className="toolbar-tools"><button className="filter-menu"><ListFilter size={14}/> Filter</button><button className="sort-menu">Due date <ArrowDown size={13}/></button></div></div>
    <DndContext sensors={sensors} collisionDetection={closestCorners} onDragStart={handleDragStart} onDragEnd={handleDragEnd} onDragCancel={()=>setActive(null)}>
     <div className="board" aria-label="Project task board">{statuses.map(status=>{const items=matching.filter(t=>t.status===status);return <BoardColumn key={status} status={status} items={items} total={tasks.filter(t=>t.status===status).length} onMove={moveTask} onAdd={()=>setModal(true)}/>})}</div>
     <DragOverlay>{active?<TaskCard task={active} overlay/>:null}</DragOverlay>
    </DndContext>
    <div className="activity-strip"><div className="activity-title"><span className="activity-icon"><Activity size={14}/></span><b>Recent activity</b><button>View all <ArrowRight size={13}/></button></div><div className="activity-items">{activity.slice(0,3).map((a,i)=><div key={a.id}><span className={`activity-dot dot-${i}`}/><p>{a.message}</p><time>{a.time}</time></div>)}</div></div>
    <footer className="page-footer"><span>COMMONPLACE · PROJECT SPACE</span><span>DRAG TO MOVE · OR USE EACH TASK’S STATUS MENU</span></footer></div>
  </section>
  {notice&&<div className="toast" role="status"><Check size={14}/>{notice}</div>}
  {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false);}}><form className="modal" onSubmit={addTask}><button className="modal-close" type="button" onClick={()=>setModal(false)} aria-label="Close"><X size={16}/></button><span className="modal-icon"><Plus size={17}/></span><div className="eyebrow">WEBSITE REFRESH</div><h2>Add a task</h2><p>Make the next bit of good work visible.</p><label>Task title<input autoFocus required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="e.g. Review launch checklist"/></label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Add context for the team"/></label><div className="form-grid"><label>Label<select value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}>{["Product","Design","Platform","Accessibility"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as Task["priority"]})}>{["High","Medium","Low"].map(x=><option key={x}>{x}</option>)}</select></label><label>Assignee<select value={draft.assignee} onChange={e=>setDraft({...draft,assignee:e.target.value})}>{members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Due date<input type="date" value={draft.due.includes("-")?draft.due:""} onChange={e=>setDraft({...draft,due:e.target.value})}/></label></div><div className="modal-actions"><button className="cancel" type="button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" type="submit"><Plus size={14}/> Create task</button></div></form></div>}
 </main>;
}

function UserRoundIcon(){return <Users size={14}/>}
function BoardColumn({status,items,total,onMove,onAdd}:{status:Status;items:Task[];total:number;onMove:(task:Task,status:Status)=>void;onAdd:()=>void}){const {setNodeRef,isOver}=useDroppable({id:`column:${status}`});return <section ref={setNodeRef} className={`column ${statusTone(status)} ${isOver?"over":""}`} aria-label={`${status} column`}><header className="column-head"><span className="column-dot"/><h2>{status}</h2><span className="column-count">{total}</span><button aria-label={`Options for ${status}`}><MoreHorizontal size={15}/></button></header><SortableContext items={items.map(t=>t.id)} strategy={verticalListSortingStrategy}><div className="column-body">{items.map(task=><TaskCard key={task.id} task={task} onMove={onMove}/>)}{items.length===0&&<div className="column-empty">Drop a task here<br/>or use its status menu.</div>}</div></SortableContext><button className="add-card" onClick={onAdd}><Plus size={14}/> Add a task</button></section>}
function TaskCard({task,onMove,overlay=false}:{task:Task;onMove?:(task:Task,status:Status)=>void;overlay?:boolean}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:task.id,disabled:overlay});const member=members.find(m=>m.id===task.assignee)??members[0];const style={transform:CSS.Transform.toString(transform),transition,opacity:isDragging ? 0.35 : 1};return <article ref={setNodeRef} style={style} className={`task-card ${overlay?"overlay":""}`}><div className="task-top"><span className="task-id">{task.id}</span><button className="drag-handle" {...attributes} {...listeners} aria-label={`Drag ${task.title} to change its position`}><GripVertical size={15}/></button></div><h3>{task.title}</h3>{task.description&&<p>{task.description}</p>}<div className="task-tags"><span className={`label ${task.label.toLowerCase()}`}>{task.label}</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority==="High"&&<span/>}{task.priority}</span></div><footer><div className="task-meta"><span className={`due ${task.due==="Oct 01"||task.due==="Oct 02"?"soon":""}`}><Clock3 size={12}/>{task.due}</span>{task.checklist&&<span className="checklist"><Check size={11}/>{task.checklist}</span>}</div><span className={`avatar ${member.tone}`} title={member.name}>{member.initials}</span></footer><label className="move-select-label"><span className="sr-only">Change task status</span><select aria-label={`Move ${task.title} to another column`} value={task.status} onChange={e=>onMove?.(task,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></article>}

